feature/phase 4
zubairaltaf10/todo-clean-architecture pull request #7
Opened 2021-09-24 14:22 UTC by zubairaltaf10

2021-09-27 16:38 UTC, bilalfaisal-ct requested changes
Please see comments, Thanks

2021-09-27 16:38 UTC, bilalfaisal-ct commented on src/Application/Events/UserCreateEvent.ts
> +        this.on('userCreated',((user)=>{
You can put all events in constants.

2021-09-27 16:38 UTC, bilalfaisal-ct commented on src/Application/User/UserService.ts
> +            var result = await commandBus.handle(createUserEntity);
Instead of var it can be const.

2021-09-27 16:38 UTC, bilalfaisal-ct commented on src/Application/User/UserService.ts
> +            if (result) {
I think the it should return if (!result) return;

and the other return statement can go as it is.

2021-09-27 16:38 UTC, bilalfaisal-ct commented on src/infrastructure/ThirdPartyClients/Email/EmailService.ts
> +        user: 'zubair.altaf@carbonteq.com',
These can be loaded from configs.

2021-09-30 09:29 UTC, bilalfaisal-ct commented on Http/Controllers/UserController.ts
> +    Register(req: Request, res: Response, next: NextFunction) {
i think the methods can be renamed to camelCase

2021-10-01 11:18 UTC, zubairaltaf10 commented on Http/Controllers/TodoController.ts
> +       return TodoService.CreateTodo(res,req.body)
camel case for methods

2021-10-01 12:21 UTC, closed without merging